#!/bin/bash
#Script to extract the non-brain tissues from the dti volumes

NII_FOLDER=$1
ACQ=$2

#Read variables form config file
BET_THR=$3
NECK_RM=$4

  echo ""
  echo " ==> BET <=="
  echo ""
  # Removing the b0 volume to create brain masks
    if [[ "$NECK_RM" == "Y" ]]; then
      echo "    --> Using Bias and Neck removal option"
      bet $NII_FOLDER/${ACQ} $NII_FOLDER/${ACQ%_*}_brain -m -f $BET_THR -B
    else
      echo "    --> Using fast brain extraction procedure"
      bet $NII_FOLDER/${ACQ} $NII_FOLDER/${ACQ%_*}_brain -m -f $BET_THR
    fi

  # Remove the unnecessary dti brain extract volume
  rm $NII_FOLDER/${ACQ%_*}_brain.nii.gz
