#!/bin/bash
#Script to perform the eddy current correction.
#See the HIGH_PERF variable in preprocessing/config_var.conf file
# TODO See NUM_VOL call image _dti.nii.gz...it is different then in INPUT_IMG variable
# TODO Use the variable initialized in the beginning of the file script in the eddy call. BVEC, BVAL ...
NII_FOLDER=$1
ACQ=$2

#Read variables form config file
HIGH_PERF=$3

echo ""
echo " ==> Eddy Correction <=="

if [[ $HIGH_PERF == "Y" ]]; then
  echo "  --> Using FSL-EDDY"
  echo ""
  #Setting the input variables to FSL-Eddy
  INPUT_IMG="$NII_FOLDER/${ACQ}_dti.nii.gz"
  BRAIN_MASK="$NII_FOLDER/${ACQ}_brain_mask.nii.gz"
  BVEC="$NII_FOLDER/${ACQ}.bvec"
  BVAL="$NII_FOLDER/${ACQ}.bval"
  OUTPUT_IMG="$NII_FOLDER/${ACQ}_eddy.nii.gz"

  # Preparing ACQ_PARAM file:
  #Read variables form config file
  ACQ_PE=`cat config/config_var.conf | grep ACQ_PE | cut -c8-10`

  # Number of volumes
  NUM_VOL=`fslnvols $INPUT_IMG`
  # Number of B0s
  NUM_B=0
  for bvalues in `cat $BVAL`; do
    if [[ $bvalues -lt 100 ]]; then
      ((NUM_B++))
    fi
  done
  case $ACQ_PE in
    "+Y" )
      echo "      --> Creating acquisition file: +Y PE"
      for (( i = 0; i < $NUM_B; i++ )); do
        echo "0 1 0 0.075" >> $NII_FOLDER/tmp_${ACQ}_acqparam.txt
      done
      ;;
    "-Y" )
      echo "      --> Creating acquisition file: -Y PE"
      for (( i = 0; i < $NUM_B; i++ )); do
        echo "0 -1 0 0.075" >> $NII_FOLDER/tmp_${ACQ}_acqparam.txt
      done
      ;;
    "+X" )
      echo "      --> Creating acquisition file: +X PE"
      for (( i = 0; i < $NUM_B; i++ )); do
        echo "1 0 0 0.075" >> $NII_FOLDER/tmp_${ACQ}_acqparam.txt
      done
      ;;
    "-X" )
      echo "      --> Creating acquisition file: -X PE"
      for (( i = 0; i < $NUM_B; i++ )); do
        echo "-1 0 0 0.075" >> $NII_FOLDER/tmp_${ACQ}_acqparam.txt
      done
      ;;
    "+Z" )
      echo "      --> Creating acquisition file: +Z PE"
      for (( i = 0; i < $NUM_B; i++ )); do
        echo "0 0 1 0.075" >> $NII_FOLDER/tmp_${ACQ}_acqparam.txt
      done
      ;;
    "-Z" )
      echo "      --> Creating acquisition file: -Z PE"
      for (( i = 0; i < $NUM_B; i++ )); do
        echo "0 0 -1 0.075" >> $NII_FOLDER/tmp_${ACQ}_acqparam.txt
      done
      ;;
  esac
  ACQ_PARAM="$NII_FOLDER/tmp_${ACQ}_acqparam.txt"

  # Preparing the INDEX file:
  indx=""
  for (( i = 1; i <= $NUM_VOL; i++ )); do
    indx="$indx 1"
  done
  echo $indx > $NII_FOLDER/tmp_eddy_index.txt
  # source preprocessing/eddy_index.sh $NII_FOLDER $ACQ
  INDEX="$NII_FOLDER/tmp_eddy_index.txt"

  # Running FSL-EDDY
  echo "      --> Running EDDY..."
  eddy --imain=$INPUT_IMG --mask=$BRAIN_MASK --index=$INDEX --acqp=$ACQ_PARAM --bvecs=$BVEC --bvals=$BVAL --out=$NII_FOLDER/${ACQ}_eddy.nii.gz
  # Removing unnecessary files
  rm $NII_FOLDER/tmp*
  # $NII_FOLDER/*.eddy_* $NII_FOLDER/*_brain_mask.nii.gz

else
  echo "  --> Using FDT-eddy_correct"
  echo ""
  #Setting the input variables to FDT-eddy_correct
  INPUT_IMG="$NII_FOLDER/${ACQ}_dti.nii.gz"
  OUTPUT_IMG="$NII_FOLDER/${ACQ}_eddy.nii.gz"

  # Find the reference image
  idx=0
  for i in `cat $NII_FOLDER/${ACQ}.bval`; do
    if [[ $i -lt 100 ]]; then
      break
    fi
    ((idx++))
  done

  eddy_correct $NII_FOLDER/${ACQ}_dti.nii.gz $NII_FOLDER/${ACQ}_eddy.nii.gz $idx

  # Removing ecclog from eddy_correct pipeline
  rm $NII_FOLDER/*.ecclog
  # $NII_FOLDER/*_brain_mask.nii.gz
fi
