#!/bin/bash
# Script to build other DTI maps based on the eigenvectors and eigenvalues given by FSL-FDT reconstruction.

MAPS_FOLDER=$1
BUILD_VR=$2
BUILD_RA=$3
BUILD_PERPD=$4

# Create the mean eigenvalues volume
fslsplit $MAPS_FOLDER/L1map_prob.nii.gz $MAPS_FOLDER/tmp_L1_ -t
fslsplit $MAPS_FOLDER/L2map_prob.nii.gz $MAPS_FOLDER/tmp_L2_ -t
fslsplit $MAPS_FOLDER/L3map_prob.nii.gz $MAPS_FOLDER/tmp_L3_ -t

NVOLUMES=`flsnvols $MAPS_FOLDER/L1map_prob.nii.gz`
for (( i = 0; i < $NVOLUMES; i++ )); do
  if [[ $i -lt 10 ]]; then
    fslmaths $MAPS_FOLDER/tmp_L1_000$i -add $MAPS_FOLDER/tmp_L2_000$i $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_000$i
    fslmaths $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_000$i -add $MAPS_FOLDER/tmp_L3_000$i $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_000$i
    fslmaths $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_000$i -div 3 $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_000$i
  fi
  if [[ $i -ge 10 &&  && $i -lt 100 ]]; then
    fslmaths $MAPS_FOLDER/tmp_L1_00$i -add $MAPS_FOLDER/tmp_L2_00$i $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_00$i
    fslmaths $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_00$i -add $MAPS_FOLDER/tmp_L3_00$i $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_00$i
    fslmaths $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_00$i -div 3 $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_00$i
  fi
  if [[ $i -ge 100 &&  && $i -lt 1000 ]]; then
    fslmaths $MAPS_FOLDER/tmp_L1_0$i -add $MAPS_FOLDER/tmp_L2_0$i $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_0$i
    fslmaths $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_0$i -add $MAPS_FOLDER/tmp_L3_0$i $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_0$i
    fslmaths $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_0$i -div 3 $MAPS_FOLDER/tmp_MEAN_EIGENVALUE_0$i
  fi
  #TODO Terminar a logica da construcao dos mapas adicionais...nao foi testado este trecho de codigo
done

if [[ BUILD_VR == "Y" ]]; then
  # Build the Volume Ratio map

fi
