#!/bin/bash
# Script to register Intrasubject sequences in order to reduce motion between each acquisition

TEMP_FOLDER=$1
NUM_SUBJ=$2
REG_ADJUSTMENT=$3
MNI_CHOSEN=`cat config/config_var.conf | grep MNI= | cut -c5-20`
LIST_ACQS=`ls $TEMP_FOLDER | grep dti`

TOTAL_VOL=0
# NUM_SUBJ=0
# for i in $LIST_ACQS; do
#   ((NUM_SUBJ++))
# done

# Creating the DTI maps probability distribution vector image file
for (( subj = 1; subj <= $NUM_SUBJ; subj++ )); do
  echo "    ==> Creating DTI maps from subject $subj"
    # if [[ $i -lt 10 ]]; then
    BET_THR=`cat config/config_var.conf | grep BET_THR= | cut -c9-12`
    NECK_RM=`cat config/config_var.conf | grep NECK_RM= | cut -c9-10`
    if [[ "$NECK_RM" == "Y" ]]; then
      # echo "    --> Using Bias and Neck removal option"
      bet $TEMP_FOLDER/dti_subject${subj}.nii.gz $TEMP_FOLDER/subject${subj}_brain -m -f $BET_THR -B
    else
      # echo "    --> Using fast brain extraction procedure"
      bet $TEMP_FOLDER/dti_subject${subj}.nii.gz $TEMP_FOLDER/subject${subj}_brain -m -f $BET_THR
    fi
    #TODO Testar os arquivos bvec e bval que vem do vector_norm
      # dtifit --data=$TEMP_FOLDER/dti_subject${subj}.nii.gz --out=$TEMP_FOLDER/subject${subj}_map --mask=$TEMP_FOLDER/subject${subj}_brain_mask.nii.gz --bvecs=$TEMP_FOLDER/gradient.bvec --bvals=$TEMP_FOLDER/bvalues.bval
      dtifit --data=$TEMP_FOLDER/dti_subject${subj}.nii.gz --out=$TEMP_FOLDER/subject${subj}_map --mask=$TEMP_FOLDER/subject${subj}_brain_mask.nii.gz --bvecs=$TEMP_FOLDER/subject${subj}_corr.bvec --bvals=$TEMP_FOLDER/subject${subj}.bval
      echo "$TEMP_FOLDER/subject${subj}_map_FA.nii.gz" >> $TEMP_FOLDER/tmp_FA_map_list.txt
      echo "$TEMP_FOLDER/subject${subj}_map_MD.nii.gz" >> $TEMP_FOLDER/tmp_MD_map_list.txt
      echo "$TEMP_FOLDER/subject${subj}_map_L1.nii.gz" >> $TEMP_FOLDER/tmp_L1_map_list.txt
      echo "$TEMP_FOLDER/subject${subj}_map_L2.nii.gz" >> $TEMP_FOLDER/tmp_L2_map_list.txt
      echo "$TEMP_FOLDER/subject${subj}_map_L3.nii.gz" >> $TEMP_FOLDER/tmp_L3_map_list.txt
      echo "$TEMP_FOLDER/subject${subj}_map_V1.nii.gz" >> $TEMP_FOLDER/tmp_V1_map_list.txt
      echo "$TEMP_FOLDER/subject${subj}_map_V2.nii.gz" >> $TEMP_FOLDER/tmp_V2_map_list.txt
      echo "$TEMP_FOLDER/subject${subj}_map_V3.nii.gz" >> $TEMP_FOLDER/tmp_V3_map_list.txt
      echo "$TEMP_FOLDER/subject${subj}_map_MO.nii.gz" >> $TEMP_FOLDER/tmp_MO_map_list.txt
      echo "$TEMP_FOLDER/subject${subj}_map_S0.nii.gz" >> $TEMP_FOLDER/tmp_S0_map_list.txt
done

fslmerge -t $TEMP_FOLDER/FAmap_prob.nii.gz `cat $TEMP_FOLDER/tmp_FA_map_list.txt`
fslmerge -t $TEMP_FOLDER/MDmap_prob.nii.gz `cat $TEMP_FOLDER/tmp_MD_map_list.txt`
fslmerge -t $TEMP_FOLDER/V1map_prob.nii.gz `cat $TEMP_FOLDER/tmp_V1_map_list.txt`
fslmerge -t $TEMP_FOLDER/V2map_prob.nii.gz `cat $TEMP_FOLDER/tmp_V2_map_list.txt`
fslmerge -t $TEMP_FOLDER/V3map_prob.nii.gz `cat $TEMP_FOLDER/tmp_V3_map_list.txt`
fslmerge -t $TEMP_FOLDER/L1map_prob.nii.gz `cat $TEMP_FOLDER/tmp_L1_map_list.txt`
fslmerge -t $TEMP_FOLDER/L2map_prob.nii.gz `cat $TEMP_FOLDER/tmp_L2_map_list.txt`
fslmerge -t $TEMP_FOLDER/L3map_prob.nii.gz `cat $TEMP_FOLDER/tmp_L3_map_list.txt`
fslmerge -t $TEMP_FOLDER/MOmap_prob.nii.gz `cat $TEMP_FOLDER/tmp_MO_map_list.txt`
fslmerge -t $TEMP_FOLDER/S0map_prob.nii.gz `cat $TEMP_FOLDER/tmp_S0_map_list.txt`

if [[ $REG_ADJUSTMENT == "Y" ]]; then
  # Registration adjustment
  echo "    ==> Making the maps adjustment to fit the ICBM template"
  source postprocessing/maps_adjustment $TEMP_FOLDER
fi

# Removing unnecessary files
# rm $TEMP_FOLDER/subject*_map* $TEMP_FOLDER/*map_list.txt

## Following the DTI raw volume template construction
# Spliting all the DTI volumes in 3D volumes
count=0
for acq in $LIST_ACQS; do
  TOTAL_VOL=`fslnvols $TEMP_FOLDER/$acq`
  fslsplit $TEMP_FOLDER/$acq $TEMP_FOLDER/tmp_${acq%.*.*}_template_ -t
  ((count++))
done

# Merging each volume through each volume
for (( subj = 1; subj <= $NUM_SUBJ; subj++ )); do
  echo "    ==> Subject $subj data of $NUM_SUBJ total subjects <=="
for (( i = 0; i < $TOTAL_VOL; i++ )); do
  echo "    --> Merging volume $i"
    if [[ $i -lt 10 ]]; then
        for (( subj = 1; subj <= $NUM_SUBJ; subj++ )); do
          echo "$TEMP_FOLDER/tmp_dti_subject${subj}_template_000${i}.nii.gz" >> $TEMP_FOLDER/tmp_mergelist_${i}.txt
        done
      fslmerge -t $TEMP_FOLDER/tmp_stack${i} `cat $TEMP_FOLDER/tmp_mergelist_${i}.txt`
      echo "      -----> Calculating the template volume ${i}"
      fslmaths $TEMP_FOLDER/tmp_stack${i} -Tmean $TEMP_FOLDER/tmp_dti_vol000${i}.nii.gz
    elif [[ $i -ge 10 && $i -lt 100 ]]; then
      for (( subj = 1; subj <= $NUM_SUBJ; subj++ )); do
        echo "$TEMP_FOLDER/tmp_dti_subject${subj}_template_00${i}.nii.gz" >> $TEMP_FOLDER/tmp_mergelist_${i}.txt
      done
      fslmerge -t $TEMP_FOLDER/tmp_stack${i} `cat $TEMP_FOLDER/tmp_mergelist_${i}.txt`
      echo "      -----> Calculating the template volume ${i}"
      fslmaths $TEMP_FOLDER/tmp_stack${i} -Tmean $TEMP_FOLDER/tmp_dti_vol00${i}.nii.gz
    fi
done
done

# Final merge between all the mean B0 and B1
echo ""
echo "    --> Creating the template from all the DTI subjects"
for name in `ls $TEMP_FOLDER | grep tmp_dti_vol`; do
    echo "$TEMP_FOLDER/$name" >> $TEMP_FOLDER/tmp_finalmerge.txt
done
fslmerge -t $TEMP_FOLDER/dti_template.nii.gz `cat $TEMP_FOLDER/tmp_finalmerge.txt`

# Creating mean DTI maps
BET_THR=`cat config/config_var.conf | grep BET_THR= | cut -c9-12`
NECK_RM=`cat config/config_var.conf | grep NECK_RM= | cut -c9-10`
if [[ "$NECK_RM" == "Y" ]]; then
  # echo "    --> Using Bias and Neck removal option"
  bet $TEMP_FOLDER/dti_template.nii.gz $TEMP_FOLDER/dti_mean_brain -m -f $BET_THR -B
else
  # echo "    --> Using fast brain extraction procedure"
  bet $TEMP_FOLDER/dti_template.nii.gz $TEMP_FOLDER/dti_mean_brain -m -f $BET_THR
fi
dtifit --data=$TEMP_FOLDER/dti_template.nii.gz --out=$TEMP_FOLDER/dti_${NUM_SUBJ} --mask=$TEMP_FOLDER/dti_mean_brain_mask.nii.gz --bvecs=$TEMP_FOLDER/subject1_corr.bvec --bvals=$TEMP_FOLDER/subject1.bval

# Loading the JHU template adequate to the DTI space
if [[ "$MNI_CHOSEN" == "MNI152lin_2mm" ]]; then
  cp `echo $FSLDIR/data/atlases/JHU/JHU-ICBM-FA-2mm.nii.gz` $TEMP_FOLDER/
  mv $TEMP_FOLDER/JHU-ICBM-FA-2mm.nii.gz $TEMP_FOLDER/tmp_JHUtemplate.nii.gz
elif [[ "$MNI_CHOSEN" == "MNI152_2mm" ]]; then
  cp `echo $FSLDIR/data/atlases/JHU/JHU-ICBM-FA-2mm.nii.gz` $TEMP_FOLDER/
  mv $TEMP_FOLDER/JHU-ICBM-FA-2mm.nii.gz $TEMP_FOLDER/tmp_JHUtemplate.nii.gz
elif [[ "$MNI_CHOSEN" == "MNI152lin_1mm" ]]; then
  cp `echo $FSLDIR/data/atlases/JHU/JHU-ICBM-FA-1mm.nii.gz` $TEMP_FOLDER/
  mv $TEMP_FOLDER/JHU-ICBM-FA-1mm.nii.gz $TEMP_FOLDER/tmp_JHUtemplate.nii.gz
elif [[ "$MNI_CHOSEN" == "MNI152_1mm" ]]; then
  cp `echo $FSLDIR/data/atlases/JHU/JHU-ICBM-FA-1mm.nii.gz` $TEMP_FOLDER/
  mv $TEMP_FOLDER/JHU-ICBM-FA-1mm.nii.gz $TEMP_FOLDER/tmp_JHUtemplate.nii.gz
fi

# Final registering with JHU template
echo "    --> Final registering with ICBM template"
# FA map
fnirt --ref=$TEMP_FOLDER/tmp_JHUtemplate.nii.gz --in=$TEMP_FOLDER/dti_${NUM_SUBJ}_FA.nii.gz --iout=$TEMP_FOLDER/dti_${NUM_SUBJ}_FA.nii.gz
fslmaths $TEMP_FOLDER/dti_${NUM_SUBJ}_FA.nii.gz -mas $TEMP_FOLDER/tmp_JHUtemplate.nii.gz $TEMP_FOLDER/dti_${NUM_SUBJ}_FA.nii.gz
# MD map
applywarp --ref=$TEMP_FOLDER/tmp_JHUtemplate.nii.gz --in=$TEMP_FOLDER/dti_${NUM_SUBJ}_MD.nii.gz --out=$TEMP_FOLDER/dti_${NUM_SUBJ}_MD.nii.gz --warp=$TEMP_FOLDER/dti_${NUM_SUBJ}_FA_warpcoef.nii.gz
fslmaths $TEMP_FOLDER/dti_${NUM_SUBJ}_MD.nii.gz -mas $TEMP_FOLDER/tmp_JHUtemplate.nii.gz $TEMP_FOLDER/dti_${NUM_SUBJ}_MD.nii.gz
# S0 map
applywarp --ref=$TEMP_FOLDER/tmp_JHUtemplate.nii.gz --in=$TEMP_FOLDER/dti_${NUM_SUBJ}_S0.nii.gz --out=$TEMP_FOLDER/dti_${NUM_SUBJ}_S0.nii.gz --warp=$TEMP_FOLDER/dti_${NUM_SUBJ}_FA_warpcoef.nii.gz
fslmaths $TEMP_FOLDER/dti_${NUM_SUBJ}_S0.nii.gz -mas $TEMP_FOLDER/tmp_JHUtemplate.nii.gz $TEMP_FOLDER/dti_${NUM_SUBJ}_S0.nii.gz

# Removing trash files
rm $TEMP_FOLDER/tmp*
rm $TEMP_FOLDER/subject*
rm $TEMP_FOLDER/*warpcoef*
rm $TEMP_FOLDER/*.log
rm $TEMP_FOLDER/dti_mean_brain.nii.gz
rm $TEMP_FOLDER/dti_mean_brain_mask.nii.gz
rm $TEMP_FOLDER/dti_${NUM_SUBJ}_V1.nii.gz
rm $TEMP_FOLDER/dti_${NUM_SUBJ}_V2.nii.gz
rm $TEMP_FOLDER/dti_${NUM_SUBJ}_V3.nii.gz
rm $TEMP_FOLDER/dti_${NUM_SUBJ}_L1.nii.gz
rm $TEMP_FOLDER/dti_${NUM_SUBJ}_L2.nii.gz
rm $TEMP_FOLDER/dti_${NUM_SUBJ}_L3.nii.gz
